"""initial

Revision ID: 001
Revises: 
Create Date: 2026-08-15 06:00:00.000000

"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), sa.ForeignKey('admin_unit.id'), nullable=True),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('name_ky', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('cropland_ha', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_unit_geom', 'admin_unit', ['geom'], unique=False, postgresql_using='gist')

    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('org', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('lang', sa.String(), server_default='ru', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_uid'),
    sa.UniqueConstraint('email')
    )

    op.create_table('field',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), sa.ForeignKey('customer.id'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('crop', sa.String(), nullable=True),
    sa.Column('sowing_date', sa.Date(), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=False),
    sa.Column('cropland_ha', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('center', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=True),
    sa.Column('district_id', sa.Integer(), sa.ForeignKey('admin_unit.id'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_field_geom', 'field', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_field_center', 'field', ['center'], unique=False, postgresql_using='gist')

    op.create_table('metric_value',
    sa.Column('unit_id', sa.Integer(), sa.ForeignKey('admin_unit.id'), nullable=False),
    sa.Column('metric_id', sa.String(), nullable=False),
    sa.Column('decade_start', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('unit_id', 'metric_id', 'decade_start')
    )
    op.create_index(op.f('ix_metric_value_metric_id_decade_start'), 'metric_value', ['metric_id', 'decade_start'], unique=False)

    op.create_table('field_metric',
    sa.Column('field_id', sa.Integer(), sa.ForeignKey('field.id'), nullable=False),
    sa.Column('metric_id', sa.String(), nullable=False),
    sa.Column('decade_start', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('field_id', 'metric_id', 'decade_start')
    )

    op.create_table('yield_forecast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.Integer(), sa.ForeignKey('admin_unit.id'), nullable=False),
    sa.Column('crop', sa.String(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('lo', sa.Float(), nullable=False),
    sa.Column('hi', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('weather_forecast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.Integer(), sa.ForeignKey('field.id'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('alert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.Integer(), sa.ForeignKey('admin_unit.id'), nullable=True),
    sa.Column('field_id', sa.Integer(), sa.ForeignKey('field.id'), nullable=True),
    sa.Column('metric_id', sa.String(), nullable=False),
    sa.Column('decade_start', sa.Date(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('agent_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_event_created_at'), 'agent_event', ['created_at'], unique=False)

    op.create_table('invoice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), sa.ForeignKey('customer.id'), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('amount_tiyin', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_status'), 'invoice', ['status'], unique=False)

    op.create_table('report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), sa.ForeignKey('customer.id'), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('decade_start', sa.Date(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_index(op.f('ix_invoice_status'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_agent_event_created_at'), table_name='agent_event')
    op.drop_table('agent_event')
    op.drop_table('alert')
    op.drop_table('weather_forecast')
    op.drop_table('yield_forecast')
    op.drop_table('field_metric')
    op.drop_index(op.f('ix_metric_value_metric_id_decade_start'), table_name='metric_value')
    op.drop_table('metric_value')
    op.drop_index('idx_field_geom', table_name='field', postgresql_using='gist')
    op.drop_index('idx_field_center', table_name='field', postgresql_using='gist')
    op.drop_table('field')
    op.drop_table('customer')
    op.drop_index('idx_admin_unit_geom', table_name='admin_unit', postgresql_using='gist')
    op.drop_table('admin_unit')
    # ### end Alembic commands ###
